"""add is_recurring column

Revision ID: fdac18940534
Revises: 2d75a14a5c8a
Create Date: 2026-08-24 10:19:09.638155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdac18940534'
down_revision: Union[str, Sequence[str], None] = '2d75a14a5c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_recurring')
    # ### end Alembic commands ###
